-- Subarctic (Clustered). GENERATED by tools/build.py - do not edit by hand.
--
-- Identical to the stock subarctic generator except for the node tree: ours is
-- the stock graph with a basin subgraph spliced into the height chain. Land
-- outside the basins is roughened, so the engine's town placer - which needs
-- level ground - concentrates towns in the basins. We never move towns; the new
-- game dialog exposes no hook for that, only terrain.
--
-- The oceans/water/mountains sliders are the stock ones and still work.
-- Strength is baked in; pick a different generator entry to change it.
--   basins ~7.1km | buildable below -0.30 | 42m of relief
function data()
return { 
		nodeTree = "town_clustering_subarctic.tree",
		climate = "::/climates/subarctic/subarctic.clima",
		desc = { 
			cargoTypeSet = { 
				cargoClassesExcluded = { },
				cargoClassesIncluded = { },
				cargoTypesExcluded = { },
				cargoTypesIncluded = { },
			},
			name = _("Subarctic (Clustered)"),
		},
		editorOnly = false,
		order = 90,
		params = {
			{ 
				
				defaultIndex = 3,
				images = { },
				key = "water",
				name = _("Water"),
				tags = { },
				tooltip = _("Adjust the size of the water body on the map."),
				uiType = "Slider",
				valueIndices = { },
				values = {
					_("Very Small"),
					_("Small"),
					_("Medium"),
					_("Large"),
					_("Very Large"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
			{ 
				
				defaultIndex = 3,
				images = { },
				key = "swamps",
				name = _("Swamps"),
				tags = { },
				tooltip = _("Adjust the number of swamps on the map."),
				uiType = "Slider",
				valueIndices = { },
				values = {
					_("Sparse"),
					_("Scattered"),
					_("Medium"),
					_("Dense"),
					_("Packed"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
			{ 
				
				defaultIndex = 3,
				images = { },
				key = "mountains",
				name = _("Mountains"),
				tags = { },
				tooltip = _("Adjust the number and height of mountains on the map."),
				uiType = "Slider",
				valueIndices = { },
				values = {
					_("Sparse"),
					_("Scattered"),
					_("Medium"),
					_("Dense"),
					_("Packed"),
				},
				yearFrom = 0,
				yearTo = 0,
			},
		},
		previewSeed = "XCwhfj8M3H",
	}
end
